defaults:
  - _self_
  - hydra: default.yaml

run_name: "exp"

dataset:
  name: "blender"
  root_dir: "data/nerf_synthetic/lego"
  img_wh: [800, 800]
  white_back: true

batch_size: 1024
num_workers: 4
chunk: 32768  # has to be smaller than batch_size * N_samples
num_epochs: 16
N_samples: 64
N_importance: 128
use_disp: false
perturb: 1.0
noise_std: 1.0
gpu: 0
save_vis_path: vis

# Adam
lr: 0.0005
momentum: 0.9
weight_decay: 0.0
scheduler:
  decay_step: [20]
  decay_gamma: 0.1

# model
model:
  depth: 8
  width: 256
  xyz_embed_dim: 10  # for positional encoding
  dir_embed_dim: 4  # for positional encoding
  skips: [4]  # add skip connection in the Dth layer
